services:
  db:
    image: postgres:17
    container_name: backend-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dbo.modelai
    ports:
      - "5432:5432"